### ISSUE TITLE
[TRACKER] Movement System

### ISSUE THREAD

**Issue by NoahShomette** [NoahShomette/bevy_ggf#4]
# Goals

Provide a relatively easy to use, adaptable, and customizable system for pathfinding and calculating an objects available moves.

# Write-Up
Adaptable, replaceable, and extensible.

Provide a basic movement system and allow it to be replaced as needed.

# Features for Release
- [x] Multiple units in tile selection
- [x] Movement Component with basic movement information
- [x] Backend to handle the movement system events and update resources with support for any implementation easily 
- [x] Default movement system implementations - advance wars style
- [x] Option to override a tiles movement cost over it's terrain cost and support it in the backend. Either through objects or through the actually tile. Ex. Building a road on the tile and updating the movement cost through that //-- Tiles currently use a unique component for their move costs. Nothing stops anything from updating this and changing it. It wont get automatically changed back to the default terrain cost if its changed though.
- [x] Option on objects to override their allowed terrain types for specific other objects. Ex. A bridge building object that allows land units to go over the water and prevents water units from going onto it. // Implemented optional ObjectMovementTypeRules. If assigned to an object it checks the tiles during the TileMoveCheck phase to see if there is an object on the tile that has a rule related to one of the rules in the objects ObjectMovementTypeRules component

**Comment by NoahShomette** [comment]
Finished as of #31 - Movement system is not complete but the mvp is done enough to work on other stuff. See #33 for tracking the next stage of the movement system
