### ISSUE TITLE
Combat System

### ISSUE THREAD

**Issue by NoahShomette** [NoahShomette/bevy_ggf#5]
# Goals

Provide the foundations of a combat system. Methods for specifying an objects range, the tiles it can attack, and the criteria to check against each tile in range to see if it has any available attacks.

# Write-Up
Adaptable, replaceable, and extensible.

Support for custom combat types. Keep two basic types in mind.
- Advanced Wars style where you assign a damage amount for each unit for each other unit in the game
- More generic strength/defense based system in the style of something like civilization.

# Features for Release
- [ ] Combat Resolver System
- [ ] Series of combat components for objects that detail the basic universal combat related stats. Range, etc. As well as base other components, attack damage, attack type, etc. The latter would not be necessary for the backend of the system however would be necessary for any default implemetations made.
- [ ] Integration with Object system to have universal buffs, nerfs, and other affects on any objects of a specific class or group. Game wide and team wide

## Notes
Range - can most likely use the movement system algorithm for this along with an optional post calculation prune to sort any special cases out.
